config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:index, :new, :create]
  end
  # Defines the root path route ("/")
  resources :bookmarks, only: [:destroy]
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[destroy]
  before_action :set_list, only: %i[new create]


  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)

  end

  def destroy
    @bookmark.destroy
    redirect_to bookmarks_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks#index</h1>
<p>Find me in app/views/bookmarks/index.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="container my-4">
  <h3>Mark new movie</h3>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Submit comment", class: "btn btn-primary" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
       <a class="navbar-brand" href="#">
        <img src="https://media.istockphoto.com/id/1285066326/fr/vectoriel/sac-en-papier-plein-de-pop-corn.webp?s=612x612&w=is&k=20&c=SxQ0hFcT6bSdyTBuyHxSKRwhXS1NtZ917yyGJNlV1Pc=" />
       </a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active mx-2 deco-none">
                <%= link_to "My lists", lists_path %>
              </li>
              <li class="nav-item mx-2 deco-none">
                <%= link_to "New list", new_list_path %>
              </li>
          </ul>
        </div>
        </div>
    </div>
    <%= yield %>

  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.istockphoto.com/id/1205073641/fr/photo/plan-plein-format-de-chaises-vides.jpg?s=1024x1024&w=is&k=20&c=WKvr70vN_lB9wLY1JpHI7yYLs_2SQtPbSEflfbzwK_w=);">
  <div class="container text-center">
    <h1>Save any kind of movies</h1>
    <p>Xxxx</p>
  </div>
</div>

<div class="container ">
  <div class="d-flex justify-content-between m-4">
    <h4>My Lists</h4>
    <div>
      <%= link_to new_list_path do%>
        <button type="button" class="btn btn-success btn-sm">Create a movie list</button>
      <% end %>
    </div>
  </div>
  <div class="wrapper">
    <% @lists.each do |list| %>
       <% if list.photo.attached? %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, crop: :fill %>')">
            <%= link_to list.name, list_path(list) %>
          </div>
       <% else %>
          <div class="card-category object-fit-cover" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('app/assets/images/backup-photo-list.jpeg')">
            <%= link_to list.name, list_path(list) %>
          </div>
       <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container my-4">
  <h3>Add a new list</h3>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit list", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.istockphoto.com/id/1205073641/fr/photo/plan-plein-format-de-chaises-vides.jpg?s=1024x1024&w=is&k=20&c=WKvr70vN_lB9wLY1JpHI7yYLs_2SQtPbSEflfbzwK_w=);">
  <div class="container text-center">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container ">
  <div class="d-flex justify-content-end m-4">
    <div>
      <%= link_to new_list_bookmark_path(@list) do%>
        <button type="button" class="btn btn-success btn-sm">Add a movie</button>
      <% end %>
    </div>
  </div>

  <div class="mb-4 wrapper">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card app/assets/stylesheets/components/_card.scss" style="width: 18rem;">
        <img alt="<%= bookmark.movie.title %>" src="<%= bookmark.movie.poster_url %>">
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.movie.overview %></p>
        </div>
        <div class="card-body">

        </div>
      </div>
      <% end %>
  </div>
</div>